apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: erikhudson/alpine-php7.2-fpm-nginx-wordpress:v3
        name: wordpress
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: "/var/www/html"
          subPath: wordpress
        - name: wordpress-php-custom
          mountPath: /usr/local/etc/php/conf.d/20-custom.ini
          subPath: 20-custom.ini
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-persistent-storage
      - configMap:
          name: wordpress-php-custom
        name: wordpress-php-custom
      nodeSelector:
        prod: "true"
      imagePullSecrets:
      - name: registry