apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/configuration-snippet: |
        add_header Content-Security-Policy upgrade-insecure-requests;
      # Lets
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"      
    name: wordpress
    labels:
      app: wordpress
      tier: frontend
spec:
  rules:
  - host: nginx.funpresp.com.br
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
        path: /
  tls:
    - hosts:
      - nginx.funpresp.com.br
      secretName: wildcard2022
  